### PR TITLE
Fix #761, Fix #760, stream reader fixes to Pause and Unregister

### LINKED ISSUE #760: Unregistering  a StreamReader's function keeps processing the stream elements until it's empty
I'd expect it to just finish processing the current batch.

### LINKED ISSUE #761: When pausing a stream based registration, the current batch is processed but its records remain in the stream

### PR DESCRIPTION
**Pull request by MeirShpilraien**
Fix #761, Fix #760, stream reader fixes to Pause and Unregister
1. Fix stream reader pause to ack after finish processing the current batch.
2. Fix stream reader unregister to stop processing more batches when finished the current batch.

### CODE REVIEW

File: src/readers/streams_reader.c [hunk 1]
```diff
@@ -84,7 +84,7 @@ typedef struct SingleStreamReaderCtx{
     long long pendingMessages;
     long long nextBatch;
     bool isRunning;
-
+    bool freeWhenDone;
```
Comment (chayim) [inline src/readers/streams_reader.c:87]: Nit: Maybe isFreeWhenDone to match isRunning?

Comment (MeirShpilraien) [reply src/readers/streams_reader.c]: Fixed

**Review by chayim — APPROVED** [review]
